version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=coredb
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=wCh29&HE&T83
    ports:
      - "5432:5432"

volumes:
  postgres_data:
